services:
  # -------- Backend: Flask + SSE --------
  - type: web
    name: dms-backend
    env: python
    plan: free
    repo: https://github.com/mehedi-88/dms-mehedi-portfolio.git
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread --threads 8 -t 120 src.main:app
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        value: dev-key
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: admin123
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://dms-frontend.onrender.com
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        value: dmsmehedis@gmail.com
      - key: gedvoprpoiluruzd
        sync: false
      - key: EMAIL_TO
        value: dmsmehedis@gmail.com

  